CREATE TABLE Superhero(
	Superhero_Id SERIAL PRIMARY KEY,
	Name TEXT NOT NULL,
	Alias TEXT NOT NULL,
	Origin TEXT NOT NULL);
	
CREATE TABLE Assistant(
	Assistant_Id SERIAL PRIMARY KEY,
	Name TEXT NOT NULL);
		
CREATE TABLE Power(
	Power_Id SERIAL PRIMARY KEY,
	Name TEXT NOT NULL,
	Description TEXT NOT NULL);
